# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email report
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Email report
        run: |
          echo "Here is the report" > report.txt
          echo "Please read it" >> report.txt
          mail -s "Report"